name: Publish Docker image

on:
  push:
    branches: ['master']

env:
 REGISTRY: docker.io

jobs:
   docker:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2
         with:
          platforms: 'linux/arm64,linux/amd64'
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
       - name: Login to DockerHub
         uses: docker/login-action@v2
         with:
           registry: ${{ env.REGISTRY }}
           username: ${{ secrets.DOCKER_USER }}
           password: ${{ secrets.DOCKER_PAT }}
       - name: Build and push
         uses: docker/build-push-action@v3
         with:
           context: ./All-tools-pod/
           push: true
           tags: madawa/all-tools:latest
