name: Build and Push Multiarch Docker Images

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Request approval
        if: github.event.type == 'pull_request'
        uses: jenkinsx/approvers@v4
        with:
          required: 1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Multiarch Images
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_USER }}/test-repo:latest
          platforms: linux/amd64,linux/arm64  # Adjust architectures as needed
          file: ./All-tools-pod/Dockerfile  # Replace with your Dockerfile path

      - name: Clean up Buildx
        uses: docker/cleanup-buildx-action@v1
