name: Multi-arch Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Authenticate with Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      # Set up QEMU (for emulation)
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build and push multi-architecture Docker images
      - name: Build and push Docker image
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --push --tag ${{ secrets.DOCKER_USER }}/test-repo:latest \
          --file ./All-tools-pod/Dockerfile ./All-tools-pod/

      # # Manual approval step
      # - name: Manual approval
      #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      #   uses: wei/github-approve-action@v2
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
